smiles-columns = [smiles]
multi-hot-atom-featurizer-mode = RIGR
config-path = exp_results/03232025_hpopt/config.yaml
data-path = data/exp_processed/03232025_split/final_combined_clean.csv
output-dir = exp_results/03232025_split/checkpoints/chemprop_weights_RIGR_ensemble_03232025
ensemble-size = 5
target-columns = [peakwavs_max, extinc_coeff, quantum_yield]
ignore-columns = [thermal_deact]
splits-column = split
task-type = regression
epochs = 200
depth = 3
dropout = 0.05
ffn-num-layers = 3
ffn-hidden-dim = 1500
message-hidden-dim = 1500
num-workers = 0
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
frzn-ffn-layers = 0
activation = RELU
aggregation = norm
aggregation-norm = 100
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
data-seed = 0
